### ISSUE TITLE
makePropMultiSigma

### ISSUE THREAD

**Issue by grahamjslater** [Caetanods/ratematrix#41]
I finally figured it out - the reason I couldn't get good mixing for the standard deviations in multi-regime models is because when makePropMultiSigma is called and up == 1 (i.e. the sds are updated, the sliding window proposal uses the proposal width for the root state, rather than the sd....

if (up == 1) {
        prop.sd <- sapply(cache.chain$chain[[iter - 1]][[3]][[Rp]], 
            function(x) slideWindowPositive(x, w_mu)) ...

sure enough, replacing w_mu with an appropriate value for the sds results in good mixing.

**Comment by Caetanods** [comment]
That is good news! Will fix that ASAP. Many thanks for the bug report.

**Comment by Caetanods** [comment]
Problem is now fixed on the development branch. To install from development branch use:

``` install_github("Caetanods/ratematrix", ref="dev", build_vignettes = TRUE) ```

**Comment by Caetanods** [comment]
Fix is now in master branch version 0.27
