### ISSUE TITLE
mergeMCMC does not work with single rate fit

### ISSUE THREAD

**Issue by acope3** [Caetanods/ratematrix#49]
Attempting to merge two MCMC's fails when the first MCMC passed is a single rate fit. My guess is this is because the mergePosterior function checks if the first object in the list inherits ratematrix_multi_chain instead of inheriting ratematrix_multi_chain or ratematrix_single_chain.

**Comment by Caetanods** [comment]
Thanks for the Bug report and I apologize for the delay in working with this. You are correct. I overlooked the single regime case when I implemented checks for argument format.

Note that the function you mention is now called `mergePosterior`.

Try the code below, it should be working now:
```
library( devtools )
install_github("Caetanods/ratematrix", ref = "master")
library( ratematrix )
data( centrarchidae )
phy.single <- mergeSimmap(phy = centrarchidae$phy.map, drop.regimes = TRUE)
single.list <- lapply(1:2, function(x) ratematrixMCMC(data = centrarchidae$data, phy = phy.single
                                                      , gen = 500, dir = "test_single") )
single.list.post <- lapply( single.list, readMCMC )
single.merge <- mergePosterior( single.list.post )
class( single.merge )
```
